config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  get '/drivers' => 'drivers#index'

  resources :owners
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  has_and_belongs_to_many :owners
end

app/models/driver.rb
class Driver < ActiveRecord::Base
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_and_belongs_to_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/driver_controller.rb
class DriverController < ApplicationController
  def index
    @drivers = Driver.all
  end

  def new
    @driver = Driver.new
  end

  def show
  end

  def edit
    @driver = Driver.find(params[:id])
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @drivers = Driver.all
  end

  def new
    @driver = Driver.new
  end

  def show
  end

  def edit
    @driver = Driver.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  def index
    @owners = Owner.all
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(params.require(:owner).permit(:name, :address))
    if @owner.save
      redirect_to owners_path
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drivers/index.html.erb
<h1>Driver's Login</h1>

app/views/home/home.html.erb
<section>
  <aside> Elit aperiam dolore possimus sunt perferendis, ad necessitatibus. Beatae blanditiis maxime officia dolorem voluptates eius? Exercitationem aliquam ipsa pariatur et quia illum minus perspiciatis dolore sapiente? Tempora delectus porro dolorem?</aside>
  <article><%= image_tag "logo.png" %></article>
  <aside>Consectetur tenetur sapiente aperiam alias incidunt harum voluptates voluptates illum repellendus quasi laboriosam autem consectetur deserunt quaerat. In dolorum quibusdam voluptatem libero aliquam! Deleniti eaque sequi dolores optio dolores! Nisi.</aside>
</section>
<section>

<h3><%= link_to 'Drivers', drivers_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Duber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/owners/index.html.erb
<h1>List of owners</h1>

<ul>
<% @owners.each do |owner| %>
  <li>
    <%= owner.name %> - <%= owner.address %> -
    <%= link_to "Details", owner_path(owner) %>
  </li>

<% end %>
</ul>

<%= link_to "Add an owner", new_owner_path %>

app/views/owners/new.html.erb
<h2>Add a new owner</h2>


<%= form_for @owner do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :address %>
  <%= f.text_field :address %><br>
  <%= f.submit %>

<% end %>

app/views/owners/show.html.erb
<h3><%= @owner.name %></h3>

<p>Address:  <%= @owner.address %></p>


<p>List of dogs</p>
<ul>
  <li>TODO</li>

</ul>